steps:
  - imports:
      pad_module_names: false
  - language_pragmas:
      align: false
  - trailing_whitespace: {}
language_extensions:
  - ExplicitNamespaces
  - FlexibleContexts
  - MultiParamTypeClasses
  - TemplateHaskell
  - TypeOperators
